// <auto-generated />
using System;
using MAVN.Service.Reporting.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MAVN.Service.Reporting.MsSqlRepositories.Migrations
{
    [DbContext(typeof(ReportContext))]
    [Migration("20191121134733_TransactionsReportEntity_v0")]
    partial class TransactionsReportEntity_v0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("report")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lykke.Service.Report.MsSqlRepositories.Entities.TransactionsReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("ActionRuleName")
                        .HasColumnName("action_rule_name");

                    b.Property<string>("Amount")
                        .HasColumnName("amount");

                    b.Property<string>("InboundWalletAddress")
                        .HasColumnName("inbound_wallet_address");

                    b.Property<string>("OutboundWalletAddress")
                        .HasColumnName("outbound_wallet_address");

                    b.Property<string>("ReceiverCustomerEmail")
                        .HasColumnName("receiver_customer_email");

                    b.Property<string>("ReceiverCustomerName")
                        .HasColumnName("receiver_customer_name");

                    b.Property<string>("ReceiverCustomerWallet")
                        .HasColumnName("receiver_customer_wallet");

                    b.Property<string>("SenderCustomerEmail")
                        .HasColumnName("sender_customer_email");

                    b.Property<string>("SenderCustomerName")
                        .HasColumnName("sender_customer_name");

                    b.Property<string>("SenderCustomerWallet")
                        .HasColumnName("sender_customer_wallet");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnName("timestamp");

                    b.Property<string>("TransactionType")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("transactions_report");
                });
#pragma warning restore 612, 618
        }
    }
}
