// <auto-generated />
using System;
using MAVN.Service.Reporting.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MAVN.Service.Reporting.MsSqlRepositories.Migrations
{
    [DbContext(typeof(ReportContext))]
    [Migration("20200629133905_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("report")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MAVN.Service.Reporting.MsSqlRepositories.Entities.TransactionReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnName("amount")
                        .HasColumnType("text");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnName("campaign_id")
                        .HasColumnType("uuid");

                    b.Property<string>("CampaignName")
                        .HasColumnName("campaign_name")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .HasColumnName("currency")
                        .HasColumnType("text");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("text");

                    b.Property<string>("LocationExternalId")
                        .HasColumnName("location_ext_id")
                        .HasColumnType("text");

                    b.Property<string>("LocationInfo")
                        .HasColumnName("location_info")
                        .HasColumnType("text");

                    b.Property<string>("LocationIntegrationCode")
                        .HasColumnName("location_integration_code")
                        .HasColumnType("text");

                    b.Property<string>("PartnerId")
                        .HasColumnName("partner_id")
                        .HasColumnType("text");

                    b.Property<string>("PartnerName")
                        .HasColumnName("partner_name")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverEmail")
                        .HasColumnName("receiver_email")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverName")
                        .HasColumnName("receiver_name")
                        .HasColumnType("text");

                    b.Property<string>("SenderEmail")
                        .HasColumnName("sender_email")
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .HasColumnName("sender_name")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnName("status")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TransactionCategory")
                        .HasColumnName("transaction_category")
                        .HasColumnType("text");

                    b.Property<string>("TransactionType")
                        .HasColumnName("transaction_type")
                        .HasColumnType("text");

                    b.Property<string>("Vertical")
                        .HasColumnName("vertical")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("Timestamp");

                    b.ToTable("transactions_report_2");
                });
#pragma warning restore 612, 618
        }
    }
}
